name: first-workflow
on: 
  push:
      branches:
        - main

jobs:
    job1:
        runs-on: ubuntu-lattest
        steps:
              - name: Checkout
                uses: actions/checkout@v6.0.2

              - name: Print Hello World
                run: echo "Hello World!"
