name: Push workflow
on:
  push:
    branches:
      - main
      - proposed-changes

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Push Event
        run: echo "This workflow is triggered by a push to the Main Branch"
