name: schedule Workflow

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  schedule-job:
    runs-on: ubuntu-lattest
    steps:
      - name: Print Scedule Trigger
        run: echo "This workflow runs every 5 minutes on a schedule"
